### ISSUE TITLE
Git

### ISSUE THREAD

**Issue by i-am-annewang** [i-am-annewang/Diary#4]
学习`git rebase`命令
+ 用来修改提交历史
+ 用来替代`git merge`
```
git rebase -i HEAD~12
i 表示interactive交互阶段，HEAD~12表示回到当前commit的第前12个commit

进入一个vim文件，编辑, s-squash表示将当前的commit与之前的commit合并，e- edit修改当前commit, d-drop删除当前commit

esc+:wq保存文件，执行
如果有冲突就解决冲突

所有-11-0的commit被统一为-11的commit

git commit --amend修改commit的内容

git push -f如果是自己的分支那么可以，-f 表示force强制更改, 如果是和其他人一起开发，那么要慎用！！！
```

---
```
git add remote .git
```
---
```
git cherry-pick commitid
```
---
``` 
git revert commitid
```

如果要修改之前的提交，可以先改动，然后
`git add`
`git commit --amend`
这样可以避免每次都需要`git rebase -i HEAD～2`，再`git commit --amend`的麻烦。

**Comment by WangHuiying** [comment]
commit 21fd244d8b15e98941278b6f2d4a2bbec53cf939
Author: annewang <351192350@qq.com>
Date:   Sun Jan 7 14:43:22 2018 +0800

    Add next.d.ts

commit 653a7ec0bd360b65d5f12df3b75d315c6e176128
Author: annewang <351192350@qq.com>
Date:   Sun Jan 7 14:43:04 2018 +0800

    Add tsconfig.json

commit efebd785a6c1e619d20a88d14e4fc6c5c55a9dbe
Author: annewang <351192350@qq.com>
Date:   Sun Jan 7 14:31:52 2018 +0800

    Use next.js to init project

**Comment by WangHuiying** [comment]
解决 git pull/push 每次都需要输入密码问题
https://github.com/yonyouyc/blog/issues/6#issue-254959263
`git config --global credential.helper store`
