### ISSUE TITLE
CSS-Grid

### ISSUE THREAD

**Issue by i-am-annewang** [i-am-annewang/Diary#5]
![image](https://user-images.githubusercontent.com/18532655/35477999-da53db2e-040c-11e8-98df-07c448951d21.png)

justify-items: stretch | start | end | center;
![image](https://user-images.githubusercontent.com/18532655/35478017-56bb46d4-040d-11e8-8e74-79da29b2595a.png)
![image](https://user-images.githubusercontent.com/18532655/35478023-6f5bcf74-040d-11e8-8eea-8c6514d4867b.png)

align-items: center;
![image](https://user-images.githubusercontent.com/18532655/35478030-99cf7cec-040d-11e8-991a-20c6c8ca59a3.png)

place-items: center center;
![image](https://user-images.githubusercontent.com/18532655/35478032-a2f5004e-040d-11e8-90bd-7f600f7af1c2.png)

![image](https://user-images.githubusercontent.com/18532655/35478047-f0d9625a-040d-11e8-8727-d7d54907c049.png)

justify-content: space-around;
![image](https://user-images.githubusercontent.com/18532655/35478051-02ee80ce-040e-11e8-9aba-b0e2d30786aa.png)

justify-content: space-between;
![image](https://user-images.githubusercontent.com/18532655/35478051-02ee80ce-040e-11e8-9aba-b0e2d30786aa.png)

align-content: stretch | start | end | space-around | space-between;
![image](https://user-images.githubusercontent.com/18532655/35478070-46a684f6-040e-11e8-995f-020ccebf018b.png)

**Comment by WangHuiying** [comment]
https://courses.wesbos.com/account/access/5a6c14911405876b8099a9b1/view/249558283

**Comment by WangHuiying** [comment]
order: 0;
![image](https://user-images.githubusercontent.com/18532655/35478443-a6f5fc56-0418-11e8-9bea-798a2f9f478c.png)

![image](https://user-images.githubusercontent.com/18532655/35478467-42d8bc30-0419-11e8-9713-832e06285601.png)

width: 100%;
![image](https://user-images.githubusercontent.com/18532655/35478490-ddc0503c-0419-11e8-8e47-d93369cfab9b.png)

**Comment by WangHuiying** [comment]
document.querySelector(".gallery");
![image](https://user-images.githubusercontent.com/18532655/35478529-c78958ee-041a-11e8-9b9f-4ae5999bc17e.png)

**Comment by WangHuiying** [comment]
![image](https://user-images.githubusercontent.com/18532655/35479144-9d9bfd60-042a-11e8-8f58-bbf703798381.png)
![image](https://user-images.githubusercontent.com/18532655/35479149-c7b37fc4-042a-11e8-8e46-0ca0b01246aa.png)
![image](https://user-images.githubusercontent.com/18532655/35479152-e72af422-042a-11e8-9864-b8e1d326dd4c.png)

**Comment by WangHuiying** [comment]
![image](https://user-images.githubusercontent.com/18532655/35479468-56a59106-0433-11e8-97ce-65814437a161.png)

**Comment by WangHuiying** [comment]
![image](https://user-images.githubusercontent.com/18532655/35479726-04e5eda6-0439-11e8-833c-212b82e2bf07.png)
https://scotch.io/bar-talk/best-vs-code-themes-of-2017
https://marketplace.visualstudio.com/items?itemName=wesbos.theme-cobalt2
